name: Issue splitter
description: Split a report into separate issues
model: openai/gpt-5
responseFormat: json_schema
jsonSchema: |-
  {
    "name": "describe_multiple_animals",
    "strict": true,
    "schema": {
      "type": "object",
      "items": {
        "type": "array",
        "properties": {
          "title": {
            "type": "string",
            "description": "Title of the issue"
          },
          "body": {
            "type": "string",
            "description": "Body of the issue"
          },
          "label": {
            "type": "string",
            "description": "Label for the issue"
          }
        },
        "required": ["title", "body", "label"],
        "additionalProperties": false
      }
    }
  }
messages:
  - role: system
    content: |
      # YOUR ROLE : 
      - You are a technical project manager. 
      - You will be given a neurodiversity report with recommendations to improve the overall solution for a diverse audience.

      # YOUR TASKS : 
      - From the report, extract and list actionable tasks
      - Detail in a technical and actionable manner the content of each task individually
      - Base your recommendations on a given external resource
      - Output the result in a JSON Array in the format detailed below

      # OUTPUT FORMAT :
      [
        {
          "title": "",
          "body": "",
          "label": ""
        },
        {
          "title":"",
          "body": "",
          "label": ""
        },
        ...
      ]
  - role: user
    content: |
      Please use the following report to detail actionable tasks :
      {{input}}
